### ISSUE TITLE
for, foreach, while. Try it from simpleworld or from any worldeditplugin

### ISSUE THREAD

**Issue by Arkdevnoder** [LittleBigMC/TNTRun-V1.0.0#3]

**Comment by OneebAamer** [comment]
hmm maybe.

**Comment by Arkdevnoder** [comment]
for($x = $this->pos1["x"]; $x <= $this->pos2["x"]; $x++){
            for($z = $this->pos1["z"]; $z <= $this->pos2["z"]; $z++){
                $block = $this->tntRun->getConfig()->get("block-id");
                $this->level->setBlock(new Vector3($x, $this->floor, $z), Block::get($block));
                $blocks += 1;

**Comment by Arkdevnoder** [comment]
Get pos 1 and pos2 from config

**Comment by OneebAamer** [comment]
Is this for creating the arena or for the block disappearings?

**Comment by Arkdevnoder** [comment]
It is crafting for arena

**Comment by Arkdevnoder** [comment]
Use double for

**Comment by OneebAamer** [comment]
ok can u make a pull request and i will merge or can u not? Its fine if u cant

**Comment by Arkdevnoder** [comment]
Im lazy...

**Comment by Arkdevnoder** [comment]
$player->getFloorY() - 1
It is wrong. Idk why
![screenshot_2016-02-29-19-59-29](https://cloud.githubusercontent.com/assets/14966273/13398397/e5c29f22-df1f-11e5-972f-49efd061865f.png)

**Comment by Arkdevnoder** [comment]
Did u check it?

**Comment by Arkdevnoder** [comment]
Damn

**Comment by Arkdevnoder** [comment]
Its problem of anticheat.

**Comment by OneebAamer** [comment]
Hmm i am trying to use this. I will tell you how it goes
