### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by ghost** [LittleBigMC/TNTRun-V1.0.0#5]
[Server] [21:02:13] [Server thread/INFO]: [ZipPluginLoader] Enabling TNTRun v1
[Server] [21:02:13] [Server thread/WARNING]: RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143
[Server] [21:02:13] [Server thread/INFO]: [ZipPluginLoader] Disabling TNTRun v1

**Comment by OneebAamer** [comment]
Ziploader doesnt work. You must use DevTools
